-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMdSonp44l0Nzp3XA
oC/JeWVZWVfOncSoxoEFvMwlFdigCgYIKoZIzj0DAQehRANCAARWnf+HpOnwCnPw
ysoEEYESA23jB84m25OaV++5V4lJMA0Jhy1uQXn1Nl6L5Saejj9X5UflwIdvMhBt
S/lF0Njy
-----END PRIVATE KEY-----